### ISSUE TITLE
Erroneous links to ATAG from the prototype

### ISSUE THREAD

**Issue by mitchellevan** [w3c/wai-wcag-supporting-documents-redesign#12]
Seen in prototype: https://w3c.github.io/wai-wcag-supporting-documents-redesign/2020-07-15-prototype.html

In the "Help improve this page" section, the links currently refer to the ATAG project in Github, such as https://github.com/w3c/wai-atag-report-tool/issues/new

These links should refer to the WAI WCAG Supporting Documents Redesign project.

Similarly, the two mailto "subject" properties currently refer to two other projects. They should refer to the Supporting Documents Redesign project.

**Comment by hidde** [comment]
Thanks for spotting! This is correct, and due to copy/pasting on my end. 

It has been fixed in the generated documents, for which we have (WIP) previews on: 

* https://draft-wcag-redesign.netlify.app/understanding/ 
* https://draft-wcag-redesign.netlify.app/techniques

The “Help improve” pattern didn't previously exist on WCAG pages, it was introduced in the WAI website redesign, so final content to be decided.
