### ISSUE TITLE
Individual techniques pages must list that they are informative/non-normative

### ISSUE THREAD

**Issue by cookiecrook** [w3c/wai-wcag-supporting-documents-redesign#4]
Individual techniques pages must list that they are informative/non-normative.

The top level Techniques page says techniques are informative, but the individual techniques documents do not. In a meeting at TPAC 2019 in Fukuoka, then Chair @awkawk acknowledged this as a problem and committed to getting it resolved.

**Comment by cookiecrook** [comment]
In addition to listing the non-normative state of the document, I suggest there be language clarifying that the technique listed is one of several potential ways to satisfy the related success criteria. As written, some of these techniques are misleading, an appear to be the _**only**_ way to satisfy the success criteria.

**Comment by hidde** [comment]
Thanks for this feedback! I've updated the requirements analysis in https://github.com/w3c/wai-wcag-supporting-documents-redesign/issues/6 to reflect your comment, and we will ensure that it is clear that Techniques are not the only way. 

[Added a link to this issue](https://github.com/w3c/wai-wcag-supporting-documents-redesign/wiki/Requirements-analysis/_compare/749b6b1639304fc7eb16580f78621820c8ce7f88...c7254ef7db9b4fc4a895f57b3d66883249568de2) from the requirements analysis so that your feedback is better included there.

Closing this issue for now.
